# Generated by Django 4.2.4 on 2023-09-13 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=75)),
                ('force', models.CharField(max_length=10)),
                ('sets', models.CharField(max_length=5)),
                ('reps', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=30)),
                ('equipment', models.CharField(max_length=50)),
                ('instructions', models.TextField(max_length=5000)),
                ('primary_muscle', models.CharField()),
                ('secondary_muscle', models.TextField(null=True)),
                ('start_img', models.CharField(null=True)),
                ('end_img', models.CharField(null=True)),
                ('gif_img', models.CharField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_app.exercise')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userExercises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
