# Generated by Django 4.2.4 on 2023-09-14 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_response',
            name='equipment',
            field=models.CharField(default='full_gym'),
        ),
        migrations.AlterField(
            model_name='survey_response',
            name='activity_level',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.7), django.core.validators.MaxValueValidator(1.8)]),
        ),
        migrations.AlterField(
            model_name='survey_response',
            name='dietary_restrictions',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
