# ci-cd.yml (Backend)
name: Backend CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  backend-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out code from the repository

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Set up Docker Buildx for multi-platform builds

    - name: Login to DockerHub
      uses: docker/login-action@v1  # Log in to DockerHub to push the Docker image
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v2  # Build and push the Docker image to DockerHub
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/shredder_back:${{ github.sha }}
        platforms: linux/amd64,linux/arm64 # Build for multiple platforms (amd64 for Windows/Mac, arm64 for newer Macs)